global:
  oss:
    bucket: &default-oss-bucket "arcadia"

# @section controller is used as the core controller for arcadia
# @param image Image to be used
# @param imagePullPolcy ImagePullPolicy
# @param resources Resources to be used
controller:
  image: kubeagi/arcadia:v0.1.0-20231207-11c8738
  imagePullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 10m
      memory: 64Mi

# @section graphql and bff server
# related project: https://github.com/kubeagi/arcadia/tree/main/apiserver
apiserver:
  image: kubeagi/arcadia:v0.1.0-20231207-11c8738
  enableplayground: false
  # update the namespace if we use different one
  dataProcessURL: http://arcadia-dataprocess:28888
  port: 8081
  ingress:
    enabled: true
    path: kubeagi-apis
    host: portal.172.22.96.167.nip.io
  oidc:
    enabled: true
    clientID: bff-client
    clientSecret: 61324af0-1234-4f61-b110-ef57013267d6
    issuerURL: https://portal.172.22.96.167.nip.io/oidc
    masterURL: https://k8s.172.22.96.167.nip.io

# @section portal for arcadia web console
portal:
  enabled: true
  kubebbEnabled: true
  image: yuntibuild/kubeagi-portal:0.1.0
  port: 80
  ingress:
    path: kubeagi-portal-public
    host: portal.172.22.96.167.nip.io

# @section fastchat is used as fastchat configurations for arcadia
fastchat:
  image:
    repository: kubeagi/arcadia-fastchat
    # Use either v0.1.0 or vllm-v0.1.0(with vllm enabled)
    tag: v0.1.0
  ingress:
    enabled: true
    host: fastchat-api.172.22.96.167.nip.io

# @section oss is used as default Object-Storage-Service for arcadia
minio:
  image:
    repository: kubeagi/minio
    tag: RELEASE.2023-02-10T18-48-39Z
  mode: standalone
  rootUser: "admin"
  rootPassword: "Passw0rd!"
  persistence:
    enabled: false
    storageClass: "openebs-hostpath"
    size: 30Gi
  ingress:
    enabled: true
    api:
      enabled: true
      insecure: false
      port: 9000
      host: minio-api.172.22.96.167.nip.io
    console:
      enabled: false
      port: 9001
      host: minio-console.172.22.96.167.nip.io
    cert:
      ipAddresses:
      - 172.22.96.167
      dnsNames:
      - minio-api.172.22.96.167.nip.io
      - minio-console.172.22.96.167.nip.io

  buckets:
    # Name of the bucket
    - name: *default-oss-bucket
      # Policy to be set on the
      # bucket [none|download|upload|public|custom]
      # if set to custom, customPolicy must be set.
      policy: "none"
      # set versioning for
      # bucket [true|false]
      versioning: false
      # set objectlocking for
      # bucket [true|false] NOTE: versioning is enabled by default if you use locking
      objectlocking: false

# @section vectorstore configures the default vectorstore utilzied by knowledgebase
vectorstore:
  url: http://arcadia-chromadb:8000
  chroma:
    distanceFunction: cosine

# @section chromadb is used to deploy a chromadb instance
chromadb:
  image:
    repository: kubeagi/chromadb
  chromadb:
    auth:
      enabled: false
    dataVolumeStorageClass: "openebs-hostpath"
    apiVersion: "0.4.18"

# @section dataprocess is used to configure data processing service
# Related project: https://github.com/kubeagi/arcadia/tree/main/data-processing
dataprocess:
  enabled: true
  image: kubeagi/data-processing:v0.1.0
  port: 28888
  env:
    minio:
      secure: "False"
      apiURL: arcadia-minio:9000
    knowledge:
      chunkSize: 500
      chunkOverlap: 50
    postgres:
      # update to the actual values
      host: postgresql
      port: 5432
      user: admin
      password: Passw0rd!
      database: arcadia
