apiVersion: v1
data:
  config: |
    systemDatasource:
      apiGroup: arcadia.kubeagi.k8s.com.cn/v1alpha1
      kind: Datasource
      name: '{{ .Release.Name }}-minio'
      namespace: '{{ .Release.Namespace }}'
    gateway:
      apiServer: 'http://{{ .Release.Name }}-fastchat.{{ .Release.Namespace }}.svc.cluster.local:8000/v1'
      controller: 'http://{{ .Release.Name }}-fastchat.{{ .Release.Namespace }}.svc.cluster.local:21001'
{{- if .Values.fastchat.ingress.enabled }}
      externalApiServer: 'http://{{ .Values.fastchat.ingress.host }}/v1'
{{- end }}
    vectorStore:
      apiGroup: arcadia.kubeagi.k8s.com.cn/v1alpha1
      kind: VectorStore
      name: '{{ .Release.Name }}-vectorstore'
      namespace: '{{ .Release.Namespace }}'
    #streamlit:
    #  image: 172.22.96.34/cluster_system/streamlit:v1.29.0
    #  ingressClassName: portal-ingress
    #  host: portal.172.22.96.136.nip.io
    #  contextPath: /arcadia
kind: ConfigMap
metadata:
  labels:
    control-plane: {{ .Release.Name }}-arcadia
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
