{{- if .Values.dataprocess.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dataprocess
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: {{ .Release.Name }}-dataprocess
spec:
  selector:
    matchLabels:
      control-plane: {{ .Release.Name }}-dataprocess
  template:
    metadata:
      labels:
        control-plane: {{ .Release.Name }}-dataprocess
    spec:
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: data-process
          image: {{ .Values.dataprocess.image }}
          ports:
            - containerPort: {{ .Values.dataprocess.port }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: DEFAULT_CONFIG
              value: {{ .Release.Name }}-config
          command:
            - "/bin/sh"
            - "-c"
            - "python /arcadia_app/src/server.py"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dataprocess
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: {{ .Release.Name }}-dataprocess
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.dataprocess.port }}
      targetPort: {{ .Values.dataprocess.port }}
  selector:
    control-plane: {{ .Release.Name }}-dataprocess
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-dataprocess
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-dataprocess
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-dataprocess
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-dataprocess
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-dataprocess
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "arcadia.kubeagi.k8s.com.cn"
    resources:
      - versioneddataset
    verbs:
      - get
      - list
  - apiGroups:
      - "arcadia.kubeagi.k8s.com.cn"
    resources:
      - datasources
      - secrets
    verbs:
      - get
  - apiGroups:
      - "arcadia.kubeagi.k8s.com.cn"
    resources:
      - versioneddataset/versioneddataset
    verbs:
      - update
{{- end }}