{{- if .Values.ops-console.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-portal
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-portal
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-portal
    spec:
      containers:
        - image: {{ .Values.ops-console.image }}
          imagePullPolicy: IfNotPresent
          name: kubeagi-portal
          ports:
          - containerPort: 80
            protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-portal
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-portal
  ports:
    - name: api
      port: {{ .Values.ops-console.port }}
      protocol: TCP
      targetPort: {{ .Values.ops-console.port }}
{{- end }}