{{- if .Values.config.embedder.enabled }}
apiVersion: arcadia.kubeagi.k8s.com.cn/v1alpha1
kind: Worker
metadata:
  name: {{ .Release.Name }}-embedder
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "2"
spec:
  displayName: 系统默认的Embedding模型服务
  description: "这是系统默认使用的Embedding模型服务"
  type: "fastchat"
  replicas: 1
  model:
    kind: "Models"
    name: {{ .Values.config.embedder.model }}
    namespace: {{ .Release.Namespace }}
{{- end }}