# permissions for end users to view conversationretrievers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: conversationretriever-viewer-role
rules:
- apiGroups:
  - retriever.kubeagi.k8s.com.cn
  resources:
  - conversationretrievers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - retriever.kubeagi.k8s.com.cn
  resources:
  - conversationretrievers/status
  verbs:
  - get
