apiVersion: arcadia.kubeagi.k8s.com.cn/v1alpha1
kind: Model
metadata:
  name: baichuan2-7b-chat
  namespace: arcadia
spec:
  displayName: "baichuan2-7b-chat"
  description: "百川智能发布的大语言模型模型,同时提供embedding模型能力"
  types: "llm,embedding"
---
apiVersion: arcadia.kubeagi.k8s.com.cn/v1alpha1
kind: Worker
metadata:
  name: baichuan2-7b-chat
  namespace: arcadia
spec:
  displayName: 百川7B对话模型服务
  description: "这是一个对话模型服务,由百川提供"
  type: "fastchat"
  model:
    kind: "Models"
    name: "baichuan2-7b-chat"
  replicas: 1
  loader: 
    image: kubeagi/minio-mc:RELEASE.2023-01-28T20-29-38Z
    imagePullPolicy: IfNotPresent
  runner: 
    image: kubeagi/arcadia-fastchat-worker:v0.2.36
    imagePullPolicy: IfNotPresent
  resources:
    limits:
      nvidia.com/gpu: "1" # request 1 GPU
